global:
  scrape_interval: 5s
  evaluation_interval: 15s
  external_labels:
    env: "dev"

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: "prometheus"  # to monitor prometheus health as well
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "agaie-agent"
    metrics_path: /metrics/
    static_configs:
      - targets: ["host.docker.internal:8080"]  # or ["localhost:8080"] for quick dev without compose